language: python
python:
  - '3.8'

services:
  - postgresql

addons:
  - postgresql: '10'

sudo: true
script:
    - python manage.py collectstatic
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test --verbosity 2

branches:
  only:
    - dev
    - master

install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa && sudo apt-get update
  - openssl aes-256-cbc -K $encrypted_cd4886b3c82d_key -iv $encrypted_cd4886b3c82d_iv -in .env.testing.enc -out .env.testing -d
  - sudo apt-get install binutils libproj-dev gdal-bin
  - sudo apt-get install libgdal-dev
  - sudo apt install -y postgresql-10-postgis-2.4

before_script:
  - pip install -r requirements.txt
  - export DJANGO_SETTINGS_MODULE=config.settings.travis
  - psql -c 'create database testdatabase;' -U postgres