language: python
python:
  - '3.8'

before_script:
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in .env.testing.enc -out .env.testing -d
  - pip install -r requirements.txt

services:
  - docker
  - postgresql

env: 
  - DJANGO_SETTINGS_MODULE=config.settings.testing

script:
    - python manage.py collectstatic 
    - python manage.py test --verbosity 2

branches:
only:
  - dev
  - master