language: python
python:
  - '3.8'

addons:
  chrome: stable



services:
  - docker 3.8
  - postgresql

install:
  - wget -N https://chromedriver.storage.googleapis.com/85.0.4183.87/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

env: "./.env.testing"

before_script:  
  - pip install -r requirements.txt
script:
  - docker-compose run web python manage.py test

branches:
only:
  - dev
  - master