language: python
python:
  - '3.8'

services:
  - postgresql


script:
    - python manage.py collectstatic
    - python manage.py test --verbosity 2

branches:
  only:
    - dev
    - master

before_script:
  - openssl aes-256-cbc -K $encrypted_cd4886b3c82d_key -iv $encrypted_cd4886b3c82d_iv -in .env.testing.enc -out .env.testing -d
  - pip install -r requirements.txt
  - sudo apt-get install binutils libproj-dev gdal-bin
  - export DJANGO_SETTINGS_MODULE=config.settings.testing