version: '3.8'

services:

  db:
    image: kartoza/postgis:12.1
    volumes:
      - postgis-data:/var/lib/postgresql
    
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db

    ports:
    - "5555:80"

    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=80

    links:
      - "db:pgsql-server"        
      
  web:
    entrypoint: /entrypoint.sh
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/marcaurel
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    env_file:
      - ./.env.dev

    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A tasks_manager worker -l INFO -B
    volumes:
      - .:/marcaurel
    env_file:
      - ./.env.dev
    depends_on:
        - web
        - redis

  redis:
    image: "redis:alpine"
    
volumes:
  postgis-data:
  static_volume: