version: '3.8'

services:

  db:
    image: kartoza/postgis:12.1
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/marcaurel
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

    depends_on:
      - db

   