version: '3.8'

services:

  db:
    image: kartoza/postgis:12.1
    volumes:
      - postgis-data:/var/lib/postgresql
    env_file:
      - ./.env.prod.db
      
  web:
    entrypoint: /entrypoint.prod.sh
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/marcaurel
    expose:
      - 8000
      - type: volume
        source: static_volume
        target: /static/staticfiles
    env_file:
      - ./.env.prod
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    environment: 
      - DJANGO_SETTINGS_MODULE=config.settings.production

    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A tasks_manager worker -l INFO -B
    volumes:
      - .:/marcaurel
    env_file:
      - ./.env.prod
    depends_on:
        - web
        - redis  
  redis:
    image: "redis:alpine"

  nginx:
    build: ./nginx
    volumes:
      - type: volume
        source: static_volume
        target: /static/staticfiles
    ports:
      - 8008:80
    depends_on:
      - web

volumes:
  static_volume: