# Generated by Django 3.1.2 on 2020-11-05 16:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('region', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('sex', models.CharField(choices=[('Masculin', 'M'), ('Féminin', 'F')], max_length=10)),
                ('level', models.CharField(choices=[('D', 'Débutant'), ('I', 'Intermédiaire'), ('A', 'Avancé')], max_length=50)),
                ('address', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.address')),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
        ),
    ]
