# Generated by Django 3.1.2 on 2020-11-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('sex', models.CharField(choices=[('Masculin', 'M'), ('Féminin', 'F')], max_length=10)),
                ('level', models.CharField(max_length=50)),
            ],
        ),
    ]
